### ISSUE TITLE
addAnnotations: Specify required fields

### ISSUE THREAD

**Issue by lisastaehli** [Esri/hub.js#100]
When adding annotations, some fields seem to be required:
- `target`
- `author`
- `description`
- `created_at` (?)

First 3 are in the example, but last one is just throwing an error when not specified. We are using the latest npm packages (last release).

**Comment by jgravois** [comment]
i was under the impression that the hosted service would hydrate `created_at` automatically and ignore anything passed in the actual request, but i'll take another look.

either way, i think you're right. more descriptive doc to explain which fields are required and how they fit into the greater domain model would be really useful.

do you think this info makes more sense in the API reference page for each method or in a Guide?

**Comment by lisastaehli** [comment]
This info should definitely go into the API reference page. For now, the sample is just very confusing, because the author is set manually in the sample whereas this does not actually work. 

If you set `author = 'some string'` it will not pass anything, as the field `author` is locked.

**Comment by jgravois** [comment]
the three fields that require a value to be supplied manually:

* target - describes what is being annotated
* description - stores the actual comment
* status - we use this one for moderation (ie: "pending" | "approved" | "removed"). 

if you don't want to moderate anonymous comments, you can just pass a placeholder string.

**Comment by jgravois** [comment]
i made some tweaks to the documentation to try and make it a little clearer what developers need to pass to `addAnnotations()`. happy to refine further if you have other suggestions.
