### ISSUE TITLE
searchAnnotations crashes when there are annotations with an empty author field

### ISSUE THREAD

**Issue by mvdbster** [Esri/hub.js#103]
Repro:

- add an annotation anonymously (results in empty `author` field)
- run `searchAnnotations(...)`
- a request is made to `https://www.arcgis.com/sharing/rest/community/users/?f=json` which fails with `message: "You do not have permissions to access this resource or perform this operation."`
- this throws an error which is not handled

Adding search option `where: "author <> ''"` _solves_ the problem, but like this, we cannot fetch the anonymous comments.

**Comment by jgravois** [comment]
thanks for the bug report. i'll find time to patch this soon.

**Comment by jgravois** [comment]
fixed in [`v1.5.0`](https://github.com/Esri/hub.js/releases/tag/v1.5.0).
