### ISSUE TITLE
searchAnnotations does not return geometry

### ISSUE THREAD

**Issue by mvdbster** [Esri/hub.js#104]
Repro:

- run `searchAnnotations({ url, authentication, returnGeometry: true })`
- request to the server is correct (`returnGeometry: true`) and returns the geometry
- returned `data` object does not contain the geometries

**Comment by jgravois** [comment]
this has been fixed in [`v1.5.0`](https://github.com/Esri/hub.js/releases/tag/v1.5.0).
thanks for the report!
