### ISSUE TITLE
Support voting on annotations

### ISSUE THREAD

**Issue by lisastaehli** [Esri/hub.js#110]
As proposed by Andrew: https://gist.github.com/ajturner/cd7b927b387b360e4c1f20a0f6a34014

We propose to add the following functions to hub.js:
* add positive or negative vote to an annotation (e.g. `addAnnotationVote`)
* get positive votes for an annotation (e.g. `searchAnnotationUpVotes`)
* get negative votes for an annotation (e.g. `searchAnnotationDownVotes`)

**Comment by lisastaehli** [comment]
Thanks for the reply @jgravois and for looking into this. So, regarding your questions:

1. Votes by anonymous users would be nice but is not a must. I feel like every website where voting is enabled requires you to login in order to do so, so that would be fine for us.
a. No, upvoting your own idea should not be possible.
b. No, multiple up- or downvotes should not be possible.  

And yes, this is how we would imagine the API calls to look like. Ideally the API would internally already sum up all up and down votes for an annotation.

**Comment by jgravois** [comment]
sounds good to me.

@tomwayson do you forsee any issues with the pseudo api above^^

**Comment by tomwayson** [comment]
@jgravois 

I wonder if we should take an `id` instead of `annotation`? Other than that, LGTM.

I agree that most of the security concerns will have to be handled either by the underlying service or the consuming application, except maybe `1.a` - I _think_ we can verify that the authenticated user is **not** the record owner.

**Comment by jgravois** [comment]
> I wonder if we should take an `id`?

in #111 i ended up using quite a few attributes from the parent annotation.
