### ISSUE TITLE
enhancement: wrapper method to summarize votes on an annotation

### ISSUE THREAD

**Issue by jgravois** [Esri/hub.js#112]
```ts
searchAnnotationVotes({
  url,
  annotation
})
  .then(response) /* =>
  {
    data: [
      {
        id,
        type: "votes",
        attributes: {
          upVotes: 3,
          downVotes: 0
        }
      }
    ]
  }
*/
```

**Comment by mvdbster** [comment]
What is the status on this issue? Is there already a way to search the annotations and have them populated with `upVotes` and `downVotes`?

**Comment by jgravois** [comment]
i got sidetracked on this one, but i'll have a PR for it _very_ soon.

**Comment by jgravois** [comment]
thx to @jParush `v1.7.0` includes [`searchSingleAnnotationVotes()`](https://esri.github.io/hub.js/api/annotations/searchSingleAnnotationVotes/) and [`searchAllAnnotationVotes()`](https://esri.github.io/hub.js/api/annotations/searchAllAnnotationVotes/).

holler if you have any trouble with them.
