### ISSUE TITLE
searchAllAnnotationVotes throws "unknown error"

### ISSUE THREAD

**Issue by mvdbster** [Esri/hub.js#122]
I am getting `'where' parameter is invalid` errors when trying [searchAllAnnotationVotes](https://github.com/Esri/hub.js/blob/67016dc988d3ab435b3bea75795d905c9c9fa3cb/packages/annotations/src/search.ts#L215)

On line [227](https://github.com/Esri/hub.js/blob/67016dc988d3ab435b3bea75795d905c9c9fa3cb/packages/annotations/src/search.ts#L227) of `hub.js/packages/annotations/src/search.ts` there is:
```
requestOptions.where += requestOptions.where ? "+AND+" : "";
```
It seems that those `+` symbols are being encoded into `%2B` instead of `%20` (blank space) which is causing at least part of problem.

This is our annotations service url: https://services9.arcgis.com/ZpmTCcECcEOnkrrK/arcgis/rest/services/hub_annotations/FeatureServer/0/

**Comment by jgravois** [comment]
resolved via #126
