### ISSUE TITLE
searchAnnotations returns votes as annotations

### ISSUE THREAD

**Issue by mvdbster** [Esri/hub.js#123]
https://github.com/Esri/hub.js/blob/67016dc988d3ab435b3bea75795d905c9c9fa3cb/packages/annotations/src/search.ts#L79

`searchAnnotations` returns votes as `type: 'annotations'`.

There is a workaround by adding `parent_id IS NULL` to the `where` clause. It would probably be better to add this filter automatically?

**Comment by jgravois** [comment]
> It would probably be better to add this filter automatically?

definitely. thanks for the report!

**Comment by jgravois** [comment]
resolved in [`v1.7.1`](https://github.com/Esri/hub.js/releases/tag/v1.7.1) 🚀. just reach out if you have any questions/problems updating.
