### ISSUE TITLE
annotations: field name 'value' cannot be added on ArcGIS Online

### ISSUE THREAD

**Issue by lisastaehli** [Esri/hub.js#124]
When attempting to add the field `value` to the annotations layer on ArcGIS Online, an error message is displayed saying that `The field name cannot be the same as an SQL keyword` and the field cannot be added with this name:

![image](https://user-images.githubusercontent.com/27951811/52357583-b2ed2f80-2a36-11e9-8a93-b1c7919ec94f.png)

In ArcGIS Pro, the field name `value` can be added without any problem.

This is just meant to be an information and could be a reason to change this field name in the future to avoid issues with ArcGIS Online.

**Comment by jgravois** [comment]
_very_ interesting. it'd probably be useful to tackle this sooner rather than later.

**Comment by tomwayson** [comment]
Thanks @lisastaehli.

@jgravois how did add that field to our services?

I wonder if this error will come up when using the API (i.e. via #113)

**Comment by jgravois** [comment]
in [`v1.7.1`](https://github.com/Esri/hub.js/releases/tag/v1.7.1) we switched to using `vote` as the fieldname (instead of `value`). 

_please_ reach out if you have any questions/problems updating.
