### ISSUE TITLE
Annotations: Down Voting deletes features which is not possible with user role 'User' 

### ISSUE THREAD

**Issue by lisastaehli** [Esri/hub.js#125]
When a user is logged in with user role 'User' (can only add items, but not delete), the down voting does not work.

deleteFeatures will throw an error message `Operation is not supported`

**Comment by jgravois** [comment]
that's strange. both downvoting and upvoting should _add_ a record. (with a `value` of -1 and 1 respectively). 

I'll dig in and investigate further when I'm back in the office tomorrow.

**Comment by lisastaehli** [comment]
This happens when the same user first up votes an annotation and then down votes it (e.g. I changed my mind about it).

**Comment by jgravois** [comment]
resolved in [`v1.7.1`](https://github.com/Esri/hub.js/releases/tag/v1.7.1) 🚀. just reach out if you have any questions/problems updating.
