### ISSUE TITLE
searchEvents() should fetch all item info in a single call to searchItems()

### ISSUE THREAD

**Issue by tomwayson** [Esri/hub.js#135]
Instead of multiple calls to `getItem()` it can probably make a single call to [searchItems()](https://esri.github.io/arcgis-rest-js/api/items/searchItems/) and pass in the item ids like `q: 'id:4aef OR id:3bed OR'`, see [the search API docs](https://developers.arcgis.com/rest/users-groups-and-items/search-reference.htm).

**Comment by jPurush** [comment]
Oh neat!

**Comment by tomwayson** [comment]
closed in #137
