### ISSUE TITLE
Getting the users of the votes

### ISSUE THREAD

**Issue by alexus37** [Esri/hub.js#136]
It would be very nice if we could get not only the number of up and down votes per annotation but as well the user who voted for it. 
This would enable us to show if the user has already voted (eg.: display arrow in blue?!) and also who else has voted.

**Comment by jgravois** [comment]
hi @alexus37 :wave:

> It would be very nice

i agree. currently though we're using [summary stats](https://github.com/Esri/hub.js/blob/22828c1791e48a8e80427bc115b9b3b670e16999/packages/annotations/src/search.ts#L221-L225) to aggregate this information so i _think_ it'd require a lot more network chatter to decorate each vote the way you describe.

another option would be for you to execute another query of your own to see whether any of the votes belong to the user that is currently logged in.

```ts
searchAnnotations({ 
  url,
  where: `parentid = '${id}' AND author = '${session.username}'`
})
  .then(response => response.features.attributes.vote)
```

**Comment by jgravois** [comment]
happy to chat further if anyone has any questions.
