### ISSUE TITLE
add a function that returns the Hub REST API base for a given environment

### ISSUE THREAD

**Issue by tomwayson** [Esri/hub.js#147]
The current logic in Hub amounts to: `https://opendata${env}.arcgis.com` where `env` is '', 'qa', or 'dev'

I think we should try to derive the `env` from the portal URL, b/c that is [available via requestOptions](https://esri.github.io/arcgis-rest-js/api/request/IRequestOptions/#portal).

**Comment by tomwayson** [comment]
NOTE: for on prem environments, it is currently `undefined` in Hub.

**Comment by tomwayson** [comment]
needs to handle org URLs like: https://dcdev.maps.arcgis.com/sharing/rest/

**Comment by tomwayson** [comment]
Based on our last discussion:

- use [getPortalUrl()](https://github.com/Esri/arcgis-rest-js/blob/4b7291031a700c25ea8bd6490557bb6b7f148218/packages/arcgis-rest-request/src/utils/get-portal-url.ts#L12) to derive the `portalUrl` frist
- Use this logic based on the `portalUrl` subdomain:
  - www = prod
  - qaext = qa
  - devext = dev
  - *.maps = prod
  - *.mapsqa = qa
  - *.mapsdevext = dev
- ignore on prem environments for now
- Use `hub` instead of `opendata` as the prefix

**Comment by jgravois** [comment]
@jPurush and i just found this:

https://github.com/Esri/hub.js/blob/bf1e7b5402d069df36197a04d925179d7a779b08/packages/domains/src/domains.ts#L11-L25
