### ISSUE TITLE
un/follow initiative

### ISSUE THREAD

**Issue by tomwayson** [Esri/hub.js#25]
See https://github.com/ArcGIS/opendata-ui/blob/c3611ae40a61ea4a4c1b24083c4454f68ac904f2/packages/ember-arcgis-layout-cards/addon/services/follow-initiative.js

**Comment by jgravois** [comment]
released in `v1.9.0` (via https://github.com/Esri/hub.js/commit/aeef22e9e645033bde8eff29cc3a1c01891b6db5)
