### ISSUE TITLE
query annotations

### ISSUE THREAD

**Issue by tomwayson** [Esri/hub.js#30]
Since annotations are backed by a feature service this will wrap [queryFeatures()](https://esri.github.io/arcgis-rest-js/api/feature-service/queryFeatures/). Events will work the same way and I previously proposed [searchEvents(eventServiceUrl, queryParams)](https://github.com/Esri/hub.js/issues/13#issuecomment-386431073). That raises few questions.

Do we use the `search` or `query` prefix? The former is consistent w/ Hub.py, the latter w/ arcgis-rest-js. I think it's more important to be consistent w/ Hub.py.

Do we pass the url as the first param? So: `searchAnnotations(annotationServiceUrl, queryParams)`. Or do we follow the pattern of just passing `opts` that is used by the [the current implementation](https://github.com/ArcGIS/opendata-ui/blob/63c3e5037f96fbef244c8b580248a4c690c34366/packages/ember-arcgis-opendata-services/addon/services/hub-annotations.js#L47-L59)?

**Comment by tomwayson** [comment]
I like it, but isn't `authentication` part of `params` - which extends [IQueryFeaturesParams](https://esri.github.io/arcgis-rest-js/api/feature-service/IQueryFeaturesParams)?

**Comment by jgravois** [comment]
close. its part of `IRequestOptions`, so we'd pick it up via [`IQueryFeaturesRequestOptions`](https://esri.github.io/arcgis-rest-js/api/feature-service/IQueryFeaturesRequestOptions/).
