### ISSUE TITLE
Updates to getType() for for pages/sites

### ISSUE THREAD

**Issue by tomwayson** [Esri/hub.js#347]
Does this need to be updated w/ the logic from `isSite()` and `isPage()` from #343?

https://github.com/Esri/hub.js/blob/570df0ec5315f42010e69e0a849d7fb6d0dfab58/packages/common/src/content.ts#L60-L70

If so, can those then be refactored to call `getType()`?

Take into account "sites are 'Site Application's on enterprise site, but 'Hub Site Applications' in hub" - @drewctate 

Finally, should it be renamed to `normalizeItemType()`?

**Comment by drewctate** [comment]
Related: #354
