### ISSUE TITLE
add searchUsers() function

### ISSUE THREAD

**Issue by juliannemarik** [Esri/hub.js#397]
## Background/Motivation
We recently released a new People Card which allows our customers to prominently feature users on their site. This feature is available on Hub, Hub Premium & Enterprise licenses. In the process of completing this feature, we discovered some of the strengths and limitations of the AGO Rest API with respect to the [Users Search](https://developers.arcgis.com/rest/users-groups-and-items/user-search.htm) and [Community User](https://developers.arcgis.com/rest/users-groups-and-items/user.htm) endpoints, namely: 

> NOTE: user profiles can have 1 of 3 types of visibility - (1) Private (2) Organization (3) Public

### Users Search
- You can pass a query string with the usernames of the people you want returned. This means you only need to hit the endpoint _one_ time with a query string like: 
```
"q=username:username1 OR username:username2 OR username:username3..."
```
- Hitting the endpoint as described above handles profile visibility, meaning that AGO will only return the subset of people which the current user has access to. 
- The endpoint is only available to _authenticated_ users. Since unauthenticated users should still be able to see public profiles, hitting this endpoint is insufficient by itself

### Community Users
- This endpoint is used to individually fetch users by their username. This means that a call needs to be made for _each_ user.
- This endpoint, unlike the Users Search endpoint which only returns the subset of people that the current user has access to, will only _limit_ the information returned for each user (i.e. `firstname`, `lastname`, and `fullname` will be empty strings if an unauthenticated users tries to access a non-public profile). 
- This endpoint is available to unauthenticated users

Because of these strengths/limitations, we ended up conditionally hitting the appropriate endpoint depending on whether the user is authenticated. 

---
In addition to the implementation above, there's an ongoing effort to add a hub-specific User Search to the Hub API. Ideally once complete, we'd just switch the above implementation over to using this hub-specific implementation; however, because the Hub API is not available in Enterprise, we'd still need to use the above implementation as a fallback. 

## Proposal
Encapsulate the above logic in a function, `getUsers()`, within `Hub.js`.

### Pseudo-Code
```
getUsers(usernames) {
  let users;

  if(online) {
    users = use Hub API User Search (whenever it becomes available)
  } else if (enterprise) {
    if(user is authenticated) {
      users = use AGO User Search endpoint and pass in a query string with the usernames 
    } else {
      users = use AGO Community User endpoint to fetch one user at a time by username and filter users by profile visibility
    }
  }

  return users
}
```

**Comment by brollison** [comment]
@tomwayson see above issue for consideration.  I know there are ongoing efforts to incorporate user search in the Hub API; however, that will not be available to Enterprise customers.  The proposal is the initial incorporation of a `getUsers()` method in Hub.js which will handle both Enterprise and Online customer, the latter being deprecated when the Hub API user search is available and incorporated.

**Comment by ajturner** [comment]
> method in Hub.js which will handle both Enterprise and Online customer, the latter being deprecated when the Hub API user search is available and incorporated.

To clarify this particular statement - Hub.js `getUsers` would not deprecate support for Online. Instead the method implementation may change to use the new API as relevant.

**Comment by tomwayson** [comment]
Thanks for opening this @juliannemarik 

Big picture what we want to do is identify what logic is unique to hub and goes above and beyond the

**Comment by tomwayson** [comment]
Before starting on this, we should decide in which package this new fn belongs. You might assume members, but we are considering consolidating that w/ other packages (see #306).

**Comment by juliannemarik** [comment]
@tomwayson I'm just getting started on this. I'm planning to hoist the function into a utility within `opendata-ui` before hoisting it to Hub.js. In terms of which package to put this fn in, I'd say possibly `search`, although it looks like that might get consolidated into `content`, so maybe content? Although I'm not sure if putting user functionality in `content` makes sense. It could also possibly live in `initiatives` since it looks like that's where teams/members might get consolidated?
I'm sure you have a more wholistic understanding of the organization though, so I'm open to suggestions.

**Comment by tomwayson** [comment]
FYI - I think this fn should be called `searchMembers()`.

You might argue it could go in the members package, but given that there's [nothing else in there](https://github.com/Esri/hub.js/issues/306#issuecomment-712310938), I'm going to remove that package. I don't think this one fn would justify the existence of a members package. As @juliannemarik points out, it could easily go in search, teams, or even sites (it's currently needed to support a card and card editor). Maybe it will end up in common.

**Comment by tomwayson** [comment]
Based on our discussion in the Hub repo, we'll call the initial implementation of this `getMemebers()` and put it in the sites package initially.

**Comment by ajturner** [comment]
Should this issue be closed now @juliannemarik ?

**Comment by juliannemarik** [comment]
Yes, thanks for the reminder!
