### ISSUE TITLE
Silent failing of addAnnotations with "old" version of Hub Annotations

### ISSUE THREAD

**Issue by lisastaehli** [Esri/hub.js#430]
We have received a bug report for Urban where a user was unable to add an annotation. We identified that the problem was that the ArcGIS Online organization of the user had an older version of the Hub Annotations layer where public annotations (Author = NULL) was not yet allowed by the schema (see error message below).

![Old_Annotations_Layer (1)](https://user-images.githubusercontent.com/27951811/100595183-dfa0c400-32fa-11eb-9819-abfa9f73da26.png)

Of course there is an obvious workaround to this (probably) edge case: the user has deleted the old annotations layer (which was anyway empty) & added a new one with the current schema. 

We would like to start a discussion on how to handle old versions of Hub Annotations layers with HubJS. In my opinion, there would be a few things that could be nice, e.g. notify the user if they are trying to connect to a feature service with an outdated schema and/or (automatically) migrate in this case. 

Please note that we are currently still on version `2.2.4` of Hub JS. If this is handled in a newer version, please let me know :)

**Comment by lisastaehli** [comment]
@tomwayson any thoughts on this :)?

**Comment by ajturner** [comment]
two approaches to consider / provide estimates @tomwayson 
- adding a migration function (I recall there was one before)
- throwing exception when creating annotation fails.

**Comment by tomwayson** [comment]
I'm looking into a migration script.

In the mean time, a potential quick fix for this would be to see if the existing service has zero records, and if so, just remove it and call [createAnnotationService()](https://esri.github.io/hub.js/api/annotations/createAnnotationService/).

**Comment by tomwayson** [comment]
I see you already did that. 🤦

**Comment by tomwayson** [comment]
FYI - this is the underlying issue regarding how the errors are swallowed:

https://github.com/Esri/arcgis-rest-js/issues/790

I think I'll have the rest-js functions throw an error if all records have an error. We could go a step further and have `addAnnotations()` and `updateAnnotations()` throw an error if _any_ records failed.

Let me know if you think the latter is necessary.

**Comment by lisastaehli** [comment]
@tomwayson thanks for the update.

I think all having errors serves our purposes as an outdated schema will cause all of them to fail :)

**Comment by tomwayson** [comment]
@lisastaehli this has been released as `6.22.3`
