### ISSUE TITLE
Default Extent not Included on IHubContent from Portal API

### ISSUE THREAD

**Issue by andrewctate** [Esri/hub.js#459]
## The Situation
**GIVEN** item `3a5510c7fe1b4cd49a870badc531cdb4` which does not have an extent (item in org `qa-pre-hub`)

_Hub API_
**WHEN** `getContentFromHub` is used to fetch the `IHubContent` by id
**THEN** an `extent` is attached to the content: `[[-134.7473,23.561],[-55.6955,50.3092]]`

_Portal API_
**WHEN** `getContentFromPortal` is used to fetch the `IHubContent` by id
**THEN** an `extent` attribute is not attached.

## Thoughts
- I toggled `isPortal` to get the `getContent` call to flip between the two APIs.
- It looks like the indexer attaches the org's(?) default extent to the dataset's attributes during the enrichment process. This is probably the reason for the discrepancy. 
- This discrepancy causes the map to disappear on the initiative template content view when an `IModel` is passed to `getContent` since it then uses the portal API (url: https://harness-qa-pre-hub.hubqa.arcgis.com/initiatives/templates/3a5510c7fe1b4cd49a870badc531cdb4/about)

**Comment by andrewctate** [comment]
@tomwayson says:
![Screen Shot 2021-01-25 at 1 01 20 PM](https://user-images.githubusercontent.com/315764/105753096-c76daf80-5f0d-11eb-9a61-90c3609a68c8.png)

**Comment by tomwayson** [comment]
resolved in #535
