### ISSUE TITLE
rip off rest-js nav toggle component

### ISSUE THREAD

**Issue by jgravois** [Esri/hub.js#50]
see https://github.com/Esri/arcgis-rest-js/pull/255, [#259](https://github.com/Esri/arcgis-rest-js/pull/259)

**Comment by tomwayson** [comment]
I don't think we have the problem of too many entries yet. ;)

**Comment by jgravois** [comment]
thanks to @dbouwman. we do now!
![screenshot 2018-09-21 09 37 37](https://user-images.githubusercontent.com/3011734/45894015-07428c00-bd82-11e8-9710-0a6b91bc6536.png)
