### ISSUE TITLE
Update get-portal-site-hostname function for Enterprise

### ISSUE THREAD

**Issue by dbouwman** [Esri/hub.js#552]
Currently `getPortalSiteHostname(subdomain, portal)` assumes the `portal.customBaseUrl` is always the instance name.

This assumption is apparently _not_ correct.

Awaiting clarification from Portal team on how to correctly derive the instance name - it _may_ be as simple as always using the `portal.portalHostname` property in which case we can reduce that fn to

```
return `${portal.portalHostname}/apps/sites/#/${subdomain}`;
```

**Comment by thomas-hervey** [comment]
for posterity, here is the hub repo issue to track the bug that caused this issue: https://devtopia.esri.com/dc/hub/issues/1278
