### ISSUE TITLE
Annotations should not require the service URL or layer id

### ISSUE THREAD

**Issue by ajturner** [Esri/hub.js#57]
Currently, searchAnnotations requires the Feature layer url:

`arcgisHub.searchAnnotations({url: annotationsUrl + "/0"}).then( response =>  {});`

This is unnecessarily complex for developers and exposes the implementation of annotations. Instead, it should default to the Org annotations, or build the right feature layer.

`arcgisHub.searchAnnotations({org: '...'})` 

```javascript
arcgisHub.getAnnotationServiceUrl("...").then(
  annotationsUrl => {
    arcgisHub.searchAnnotations({url: annotationsUrl}).then( response =>  {});
  }
);
```

**Comment by jgravois** [comment]
i created a (duplicate) issue for this. whoops!

tracking in #65
