### ISSUE TITLE
Annotation CRUD should not need adds: updates: deletes

### ISSUE THREAD

**Issue by ajturner** [Esri/hub.js#58]
It's odd that addAnnotations requires `adds: []` - which seems redundant to the actual name. This is because the function is a thin wrapper to feature service, but unnecessary for these focused functions. 

```js
arcgisHub.addAnnotations({url: annotationsUrl + "/0", adds: [
              {attributes: {description: "Test Anonymous", target: "none", author: "Hamilton"}}
            ]}).then( response => {
              console.log("addAnnotations", response);
          });
```

should become

```js
arcgisHub.addAnnotations({url: annotationsUrl, annotations: [
              {attributes: {description: "Test Anonymous", target: "none", author: "Hamilton"}}
            ]}).then( response => {
              console.log("addAnnotations", response);
          });
```

**Comment by jgravois** [comment]
an option with perhaps less cognitive overhead than introducing _yet another_ interface would be to make a breaking change to `arcgis-rest-js` to use the word `"features"` instead of `"adds/updates/deletes"`.

**Comment by tomwayson** [comment]
@ajturner - you make a valid point, but I don't think the TS gymnastics in #63 are worth it. @jgravois brings up a good point re: `features` in rest-js. Perhaps the current signatures w/ `adds`, `updates`, etc is too leaky an abstraction (hardly an abstraction at all) and is not as clean an interface as using `annotations` and `features`, but it's at least consistent all the way down the stack (Hub.js -> rest-js -> REST API) and familiar to esri devs.

I don't think we should change the way we're doing it.

**Comment by tomwayson** [comment]
@jgravois  it looks like we went w/ `features` here: https://github.com/Esri/ember-arcgis-server-services/#feature-service

**Comment by jgravois** [comment]
now that rest-js `v1.14.1` has been released, in hub.js wenow support _both_ `features` and `adds/updates`.
