### ISSUE TITLE
searchContent results should be an array of IHubContent

### ISSUE THREAD

**Issue by tomwayson** [Esri/hub.js#606]
Currently `results` is an array of the `attributes` returned for each record when querying the Hub API:

https://github.com/Esri/hub.js/blob/40a59953fe0504a34f81f4c7e0decda75e740c14/packages/search/src/content/helpers/convert-hub-response.ts#L138-L150

And when querying the portal API, it is just the results (`IITem[]`):

https://github.com/Esri/hub.js/blob/40a59953fe0504a34f81f4c7e0decda75e740c14/packages/search/src/content/helpers/convert-portal-response.ts#L27

I propose that we:
- for Hub API we map the records to `datasetToContent()`
- for for the Portal API we map the results to `itemToContent()`

This should not be much of a breaking change, especially in the case of Portal since `IHubContent` is a superset of `IItem`. In the case of Hub, `datasetToContent()` may be slightly different (mostly corrections), and may omit some enrichments.

I understand that `searchContent()` is in use for DCAT, if there are omissions on the Hub side that are needed by that, we can add them to `IHubContent` and `datasetToContent()`.

**Comment by ajturner** [comment]
@tomwayson this is a good suggestion using the façade pattern. 

Since we're also looking forward to a "v4" search API would this pattern work where we might add something like an internal `searchv4ToContent()` method for transformations from that (ideally simplified) response into a Content object?

**Comment by tomwayson** [comment]
Good idea @andrewctate 

I suggest we expose  these lines:

https://github.com/Esri/hub.js/blob/5816e0d0943a26a556717fe9cf21930e0029bbe9/packages/search/src/content/index.ts#L133-L156

as `searchDatasets(request: IContentSearchRequest): { data: DatasetResource[] }`

So it still takes a search request, but returns essentially the raw JSONAPI response from the API.

As you propose `searchContent()` would  call that internally, but then return `response.data.map(datasetToContent)`

**Comment by ajturner** [comment]
> The fate of the current editor is uncertain, but in the short term we may well simply update those paths to match the `attributes` object in the v3 API response. And, again, customers will be able to see exactly what these paths refer to by inspecting the naked responses from the v3 API.

This is an intriguing concept that the API provides the documentation for the Editor. The editor can evolve to in fact be drive by the API through introspection of the response object model or the self-describing JSON-Schema of the API which would provide additional element information such as description, source, requirements, etc. 

I'm curious how we can base the Editor and configuration on the V3 API which we are considering deprecating for the V4 API. This might be manageable with either version migration or dynamic version transformations (e.g. maintain v3 stored configuration but fetch object values from a v3-v4 mapping).

**Comment by andrewctate** [comment]
@tomwayson since that sounds good to you, we can cancel the meeting today. I'm glad I was able to convey my thoughts asynchronously.

@ajturner you're hitting on important questions. As I think that a self-describing JSON-Schema for the API could be really useful. JSON-Schema descriptions for the configuration options of each export format is related line of thought (I think you mentioned this in Confluence). But, I need a clearer understanding of the requirements of new editing experience before putting the pieces to work in a cohesive plan.

I think a migration from v3 to v4 would look a lot like our planned migration from internal dataset schema to v3, including both options you've enumerated.

**Comment by tomwayson** [comment]
@andrewctate 

Were you using any of the other properties on the response other than `results` (i.e. `count`, total`, hasNext`, `next()`, `aggregations`)? B/c the plan I outlined above did not account for that.

**Comment by andrewctate** [comment]
Yes, I use the `next` and `hasNext` properties ([ref](https://github.com/koopjs/koop-provider-hub-search/blob/main/src/model.ts#L30)). Does that cause you difficulty?

**Comment by tomwayson** [comment]
I was proposing a `searchDatasets()` fn that would return the raw results from a Hub API request like https://hub.arcgis.com/api/v3/datasets?filter[type]=PDF

```
{
  "data": [{
    id: "4ef",
    type: "dataset",
    attributes: {}
    ...
   }],
  "meta": {
    "apiRoot": "https://hub.arcgis.com/api/v3/",
    "queryParameters": {
      "filter": {
        "type": "PDF",
        "isCancelled": "eventsEq(false)",
        "status": "not(private,draft,planned)",
        "endDate": "eventsBefore(1630608647222)"
      }
    },
    "request": "https://hub.arcgis.com/api/v3/datasets?filter[type]=PDF",
    "resourceRoot": "https://hub.arcgis.com/api/v3/datasets",
    "stats": {
      "totalCount": 106324,
      "count": 10,
      "aggs": {}
    },
    "page": {
      "start": 1,
      "size": 10,
      "nextStart": 11
    },
    "took": 36,
    "total": 106324,
    "datasetsMatching": {
      "onlySemanticFields": [],
      "onlyNonSemanticFields": [],
      "both": []
    }
  },
  "links": {
    "first": "https://hub.arcgis.com/api/v3/datasets?filter%5Btype%5D=PDF&page%5Bnumber%5D=1&page%5Bsize%5D=10",
    "next": "https://hub.arcgis.com/api/v3/datasets?filter%5Btype%5D=PDF&page%5Bnumber%5D=2&page%5Bsize%5D=10",
    "last": "https://hub.arcgis.com/api/v3/datasets?filter%5Btype%5D=PDF&page%5Bnumber%5D=10633&page%5Bsize%5D=10"
  }
}
```

I guess I could add `hasNext` and `next()` to that, but I don't want to get into the business of reformatting the `meta` into the shape of the search response.

This won't be a drop in replacement, you'll still have update your code to use `data.map(d => d.attributes)` instead of `results`.

Will that work for you?

**Comment by andrewctate** [comment]
I can work with that, even without the `next` function. The main point is that it still needs to accept an `IContentSearchRequest`.
