### ISSUE TITLE
crud/search shouldn't require adding "/0" to the annotationsUrl

### ISSUE THREAD

**Issue by jgravois** [Esri/hub.js#65]
from @ajturner:

> Currently, searchAnnotations requires the Feature layer url:

> `arcgisHub.searchAnnotations({url: annotationsUrl + "/0"}).then( response =>  {});`

> This is unnecessarily complex for developers and exposes the implementation of annotations. Instead, it should default to the Org annotations, or build the right feature layer.

> `arcgisHub.searchAnnotations({org: '...'})` 

> ```javascript
> arcgisHub.getAnnotationServiceUrl("...").then(
>   annotationsUrl => {
>     arcgisHub.searchAnnotations({url: annotationsUrl}).then( response =>  {});
>  }
> );
> ```

**Comment by tomwayson** [comment]
agree, but let's wait until we finalize the service/view structure
