### ISSUE TITLE
ArcGISContext guide feedback

### ISSUE THREAD

**Issue by dbouwman** [Esri/hub.js#713]
Please take a look at the Guide - https://esri.github.io/hub.js/guides/context/ and leave comments on this issue

**Comment by drspacemanphd** [comment]
Awesome job @dbouwman! I'll dig into the code more closely when I have a bit more time, but wanted to ask about the Context manager, particularly this line:
`const ctxMgr = await ArcGISContextManager.create();`

I assume that if one were to do the following: `ctxMgrOne` and `ctxMgrTwo` would be two different instances of the context manager that could potentially return two different contexts? 

```
const ctxMgrOne = await ArcGISContextManager.create();
const ctxMgrTwo = await ArcGISContextManager.create();
```

If that's the case I also assume it's up to the client (whatever form it takes) to ensure it manages the context manager properly, e.g. for our Ember App, there should likely only be one context manager instantiated?

**Comment by dbouwman** [comment]
@drspacemanphd correct - this is not _forcing_ a singleton, so an app can manage as many contexts as it wants... which is good b/c there are a few places in hub where we manage two identities at the same time.

That said - _typically_ we'd expect an app to manage a single instance, and as the auth state changes, update the app's "state system" w/ the new `.context`.

**Comment by ajturner** [comment]
- add example for setting different context values (your current example shows failure, but not the correct pattern)
- Should the [Authentication guide](https://esri.github.io/hub.js/guides/authentication/) be updated / replaced b/c of Context?
- for Framework - start more generally before talking about Ember specifically. Ember is a hub-specific internal consideration
- Provide example code for using Context w/ Hub.js functions and with Components and in Node

**Comment by dbouwman** [comment]
@ajturner - thanks for the feedback

The context is designed to be immutable so you can't set anything on an instance, you can only create new instances... and that's what the context manager does for you as you call methods on it. I'll try to make this clearer.

I'll definitely update the Frameworks section - I know ember so it was easy to write that, but I'll add a more generic section ahead of that. 

I'll expand the examples and show something that's node specific. 

I plan to add another guide to hub-components talking about how to pass this sort of configuration into a component; tldr - use `portal="https://myserver.com/gis`` or set `context` on the element. 

In the Q & A section I address some aspects of your other two questions... in general, don't think we want to pass a "context" into Hub.js functions, simply because it's a big object, and I think functions should take the minimal params they actually need. Context does have getters for `IHubRequestOptions`, `IUserRequestOptions` and `IRequestOptions` - allowing an app to easily get those various interfaces when making calls to Hub.js/Rest-js functions.

I do think the Authentication page should be updated, to suggest writing functions w/ using the limited types possible, this making it much easier to re-use the functions, and make mention of using Context to get easy access to those types.

**Comment by tannerjt** [comment]
This looks great @dbouwman!.  

From the JSAPI auth perspective, the approach should integrate well and the process is to pass in an `ICredential` to the [registerToken](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-IdentityManager.html#registerToken) method on the [IdentityManager](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-IdentityManager.html) class.  

`ICredential` can be obtained from the `UserSession.toCredential()` method.  Since `session`(*UserSession*) is a property of `IArcGISContext`, it looks like the JSAPI can have a token properly registered as such: `esriId.registerToken(ctxMgr.context.session.toCredential())`.

**Comment by sonofflynn89** [comment]
@dbouwman thanks for doing this! Looks great!

The only comment I have is about namespacing. Some hub-specific properties are prefixed with `hub` (`hubEnabled`, `hubRequestOptions`, etc.). Others are not (`communityOrgId`, `discussionsServiceUrl`, etc.). If we're plan on proposing this context class to outside teams, wouldn't we want something more consistent?

**Comment by dbouwman** [comment]
Thanks for the questions @sonofflynn89 - good point on `communityOrgId` - that is hub specific, but we've always used it as `communityOrgId` so I just went with that. I'll confer with others but I think prefixing makes sense.

As for discussions - we intend for that to be platform-wide feature, so it's not prefixed.

**Comment by dbouwman** [comment]
@tannerjt  - thanks for the JSAPI example - I tried looking for that but just got lost. I'll add that into the Guide

**Comment by dbouwman** [comment]
Guide is updated and published. Any additional feedback will be addressed in other issues.
