### ISSUE TITLE
Vulnerability @esri/hub-common@9.29.0: minimist 1.2.0

### ISSUE THREAD

**Issue by lisastaehli** [Esri/hub.js#779]
Our security scan in urban-designer as well as `npm audit` revealed a critical vulnerability that stems from the hub-common package. 

─┬ @esri/hub-common@9.29.0
 └─┬ fast-xml-parser@3.2.4
   └─┬ opencollective@1.0.3
     └── minimist@1.2.0

![image](https://user-images.githubusercontent.com/27951811/166290428-4f3b7241-92c3-435a-a78d-a3dee7ff442e.png)

Would it be possible to bump the `fast-xml-parser` to the any version after 3.10.0 (https://github.com/NaturalIntelligence/fast-xml-parser/tree/3.10.0)? The `opencollective` library was removed with this release & would remove the vulnerability.

**Comment by rweber-esri** [comment]
@brollison 

It looks like this vulnerability was patched as part of @tomwayson [PR-788](https://github.com/Esri/hub.js/pull/788/files#diff-50d7c39a9430d37971aa76858165ab4f7921c4cc4340b28e9b673ce6982e63cfR19) and released in [@esri/hub-common@9.31.2](https://github.com/Esri/hub.js/releases/tag/%40esri%2Fhub-common%409.31.2).
